### ISSUE TITLE
ruby 3.2.0: Could not open library libcld3.bundle'

### ISSUE THREAD

**Issue by josh-m-sharpe** [akihikodaki/cld3-ruby#39] opened 2023-02-09 16:25 UTC
updating a ruby app to 3.2.0 (from 3.0.5).  Gemfile has cld3 locked to 3.5.0

On invoking this library:

Could not open library '/Users/jsharpe/.rvm/gems/ruby-3.2.0@ctm3/gems/cld3-3.5.0/lib/cld3/../../ext/cld3/libcld3.bundle'

Confirmed the file libcld3.bundle is nowhere to be found.  It exists in a similiar location for ruby 3.0.5

**Comment by jsharpe-ctm** [comment] 2023-02-09 17:16
I think this is a broader 3.2.0 building native extensions issue.  Will close if I find root cause.

**Comment by josh-m-sharpe** [comment] 2023-02-09 17:52
Hmm, it appears that it's only this libcld3.bundle file.  I copied the one generated with ruby `3.0.5` into the `3.2.0` path and then things work.  

I also confirmed the file is generated when building with ruby 3.1.3. 

So it just seems like it's 3.2.0 at this point not playing nice.

**Comment by josh-m-sharpe** [comment] 2023-02-09 17:52
Possibly related:
https://github.com/rubygems/rubygems/issues/6205

**Comment by akihikodaki** [comment] 2023-02-11 04:37
This is a duplicate of #37.

**Closed as completed by akihikodaki** 2023-02-11 04:37 UTC
Labels: duplicate
